// Generated by scripts/write-migration-manifest.mjs. Do not edit by hand.
// Regenerate with `npm run migrations:manifest` after adding a migration.

/** Every migration this build of the code expects to have been applied. */
export const EXPECTED_MIGRATIONS: readonly string[] = [
  "20260811000000_init",
  "20260811120000_client_names_and_discipline",
  "20260811170000_self_service_portals_and_whatsapp_shares",
  "20260812130000_shareable_documents_beyond_submissions",
  "20260814200000_field_agent_links",
  "20260814230000_practice_needs",
  "20260815090000_supervised_field_review",
  "20260819120000_share_passcode",
  "20260819130000_client_status_other",
  "20260819140000_submission_processed",
  "20260819150000_practice_safe_mode",
  "20260819180000_drop_trigram_index",
  "20260819220000_template_sirp"
];
