// Generated by scripts/write-migration-manifest.mjs. Do not edit by hand.
// Regenerate with `npm run migrations:manifest` after adding a migration.

/** Every migration this build of the code expects to have been applied. */
export const EXPECTED_MIGRATIONS: readonly string[] = [
  "20260811000000_init",
  "20260811120000_client_names_and_discipline",
  "20260811170000_self_service_portals_and_whatsapp_shares",
  "20260812130000_shareable_documents_beyond_submissions"
];
